name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.PAT_TOKEN }}"
      - name: test
        run: |
          echo ${{ steps.dependabot-metadata.outputs.updated-dependencies-json }}
          echo ${{ steps.dependabot-metadata.outputs.dependency-names }}
          echo ${{ steps.dependabot-metadata.outputs.dependency-type }}
          echo ${{ steps.dependabot-metadata.outputs.update-type }}
          echo ${{ steps.dependabot-metadata.outputs.alert-state }}
          echo ${{ github.repository }}
          echo ${{ github.triggering_actor	}}
          echo ${{ github.event.pull_request.html_url }}
        shell: bash
